- name: Download latest leaderboard
        run: |
          SHARE_URL="https://1drv.ms/u/c/efa322e5fea81d64/IQDeADwxuDj1Qaixwgxj9a5FAcZBu3d5ff9AsrVfwEllqnE?e=X56r4J"
          B64=$(echo -n "$SHARE_URL" | base64 | tr '/+' '_-' | tr -d '=')
          curl -L "https://api.onedrive.com/v1.0/shares/u!${B64}/root/content" -o leaderboard.json
