name: Update Leaderboard

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download latest leaderboard
        run: |
          curl -L "https://1drv.ms/u/c/efa322e5fea81d64/IQDeADwxuDj1Qaixwgxj9a5FAcZBu3d5ff9AsrVfwEllqnE?e=X56r4J" -o leaderboard.json

      - name: Show downloaded file
        run: |
          ls -l
          head -5 leaderboard.json

      - name: Commit changes
        run: |
          git config user.name "leaderboard-bot"
          git config user.email "actions@github.com"

          git add leaderboard.json

          if git diff --cached --quiet; then
            echo "No changes detected"
          else
            git commit -m "Update leaderboard data"
            git push
          fi
